blog-app/config/routes.rb
Rails.application.routes.draw do

  Rails.application.routes.draw do
    resources :articles
    root 'welcome#index'
  end

end

blog-app/app/models/article.rb
class Article < ActiveRecord::Base
end

blog-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog-app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  def index
    @articles = Article.all
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

blog-app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog-app/app/helpers/application_helper.rb
module ApplicationHelper
end

blog-app/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog-app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog-app/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
      </tr>
  <% end %>
</table>

blog-app/app/views/articles/new.html.erb
<h1> New Articles</h1>

<%= form_for :article, url: articles_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

blog-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog-app/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>